FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y lsb-release ca-certificates apt-transport-https software-properties-common

RUN add-apt-repository -y ppa:ondrej/php

RUN apt update
RUN apt install -y supervisor iputils-ping libboost-dev libxml2-dev
RUN apt install -y php8.2-cli php8.2-fpm php8.2-curl php8.2-mbstring \
    php8.2-xml php8.2-intl \
    php8.2-zip php8.2-xdebug php8.2-pgsql php8.2-bcmath php8.2-amqp \
    php8.2-imagick php8.2-gmp php8.2-redis

#RUN update-alternatives --set php /usr/bin/php8.2

#RUN apt install -y curl
#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN mkdir /run/php

CMD ["supervisord", "-c", "/etc/supervisor/supervisor_nodeamon.conf"]

EXPOSE 9000